# Generated by Django 3.2.7 on 2021-09-13 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('money_added', models.IntegerField(default=0)),
                ('money_paid', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
