# Generated by Django 3.2.7 on 2021-09-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_alter_wallet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pay.wallet')),
            ],
        ),
    ]
